<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>ivg</string>
	<key>scopeName</key>
	<string>source.ivg</string>
	<key>fileTypes</key>
	<array>
		<string>ivg</string>
	</array>
	<key>patterns</key>
	<array>
			<dict>
				<key>include</key>
				<string>source.impd#stringEscape</string>
			</dict>
			<!-- PATH DSL block: PATH [ ... ] with IVG path compounds (moved before generic groups to avoid overshadow) -->
			<dict>
				<key>name</key>
				<string>meta.path.dsl.ivg</string>
				<key>contentName</key>
				<string>meta.group.impd</string>
				<key>begin</key>
				<string>(?i)\b(PATH)\s*(\[)</string>
				<key>end</key>
				<string>(\])</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>support.function.instruction.ivg</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>meta.group.impd</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>meta.group.impd</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>support.function.path.ivg</string>
						<key>match</key>
						<string>(?i)\b(move-to|move-angle|line-to|line-angle|bezier-to|arc-to|arc-sweep|arc-move|close|rect|polygon|ellipse|text|path|anchor|cursor)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.variable.impd, variable.other.impd</string>
						<key>match</key>
						<string>(\$[a-zA-Z0-9$_.]+)</string>
					</dict>
					<dict>
						<key>name</key>
						<string>constant.numeric.impd</string>
						<key>match</key>
						<string>[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?(\s*%)?</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.impd</string>
					</dict>
				</array>
			</dict>
		<dict>
			<key>name</key>
			<string>meta.group.ivg</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ivg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.impd</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.color.ivg</string>
			<key>match</key>
			<string>(?&lt;![a-zA-Z0-9])#[0-9A-Fa-f]{6,8}</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.ivg</string>
			<key>match</key>
			<string>(?&lt;![a-zA-Z0-9])#[0-9A-Fa-f]{2}</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.colors.ivg</string>
			<key>match</key>
			<string>(?i)\b(none|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.other.ivg</string>
			<key>match</key>
			<string>(?i)\b(linear|radial|butt|round|square|bevel|miter|non-zero|even-odd)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.align.ivg</string>
			<key>match</key>
			<string>(?i)\b(left|center|right|top|middle|bottom)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.ivg</string>
			<key>match</key>
			<string>(?i)\b(yes|no)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.option.ivg</string>
			<key>match</key>
			<string>(?i)\b(align|clip|width|height|stretch|opacity|anchor|rule|size|color|outline|at)\b(?=\s*:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.paint.ivg</string>
			<key>match</key>
			<string>(?i)\b(gradient|pattern|from|to|stops|relative)\b(?=\s*:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.options.ivg</string>
			<key>match</key>
			<string>(?i)\b(aa-gamma|curve-quality|pattern-resolution)\b(?=\s*:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.stroke.ivg</string>
			<key>match</key>
				<string>(?i)\b(caps|joints|dash|dash-offset|miter-limit|type)\b(?=\s*:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.arc.ivg</string>
			<key>match</key>
			<string>(?i)\b(turn|large|rotate)\b(?=\s*:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.arc-values.ivg</string>
			<key>match</key>
				<string>(?i)(?<!-)\b(cw|ccw|pie|chord|sweep)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.color.ivg</string>
			<key>match</key>
			<string>(?i)\b(rgb|hsv)(?=\()</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.instruction.ivg</string>
			<key>match</key>
				<string>\b(RECT|LINE|ELLIPSE|POLYGON|PATH|TEXT|IMAGE|STAR|WIPE)\b</string>
		</dict>
		<!-- PORTED from older: specialized PATH(svg:[ ... ]) block with SVG path command highlighting -->
		<dict>
			<key>name</key>
			<string>meta.path.ivg</string>
			<key>contentName</key>
			<string>meta.group.impd</string>
			<key>begin</key>
			<string>(?i)\b(PATH)\s((svg):)\s*(\[)</string>
			<key>end</key>
			<string>(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.instruction.ivg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.label.impd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.impd, variable.parameter.impd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.group.impd</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.group.impd</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.path.ivg</string>
					<key>match</key>
					<string>(?i)\b(move-to|move-angle|line-to|line-angle|bezier-to|arc-to|arc-sweep|arc-move|close|rect|polygon|ellipse|text|path|anchor|cursor)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.svg.path.ivg</string>
					<key>match</key>
					<string>(?i)[MLHVCSQTAZ]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.variable.impd, variable.other.impd</string>
					<key>match</key>
					<string>(\$[a-zA-Z0-9$_.]+)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.impd</string>
					<key>match</key>
					<string>[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?(\s*%)?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.impd</string>
				</dict>
			</array>
		</dict>
			<dict>
				<key>name</key>
				<string>support.function.instruction.ivg</string>
				<key>match</key>
				<string>(?i)\b(bounds|context|options|pen|fill|mask|reset)\b</string>
			</dict>
		<dict>
			<key>name</key>
			<string>support.function.transformation.ivg</string>
			<key>match</key>
			<string>(?i)\b(offset|scale|rotate|shear|matrix)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.instruction.ivg</string>
			<key>match</key>
			<string>(?i)\b(define\s+font|define\s+image|define\s+path|define\s+pattern|font|TEXT|IMAGE|PATH)\b</string>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
</dict>
</plist>
